?start: sum

?sum: sum "+" term   -> plus
    | sum "-" term   -> minus
    | term

?term: term "*" factor  -> times
     | term "/" factor  -> divide
     | factor

?factor: "-" factor     -> neg
       | power

?power: atom "^" power  -> power
      | atom

?atom: "log" atom "base" atom  -> logbase
     | "(" sum ")"             -> paren
     | NUMBER                  -> num

%import common.NUMBER
%import common.WS
%ignore WS
